### ISSUE TITLE
To sever? Or not to server?

### ISSUE THREAD

**Issue by btupper** [BigelowLab/ColbyForecasting2025#1]
That is the question @SeascapeScience 

I haven't heard back from IT regarding a server even after a 2nd message.  I was about to ping Kevin directly, when it occurred to me to see how big the cropped Brickman data (and other data) really are.  The answer is not very much at 23MB. It includes 83 brickman files, 3 coastline files (coarse, medium and detailed) and a small file with example location (happens to be the Gulf of Maine buoys).  All other data the students generate for themselves. 

```
btupper@ecocast ColbyForecasting $ ll
total 12
drwxrwsrwx 8 btupper ecocast 4096 Dec  6 11:21 ColbyForecasting2025
drwxrwsr-x 5 btupper ecocast 4096 Dec  5 10:00 ColbyForecasting2025.wiki
drwxrwsr-x 7 btupper ecocast 4096 Dec  5 12:09 data
btupper@ecocast ColbyForecasting $ du -hs data
23M	data
``` 

We could consider having students use their own laptops, and have them download the data from a Google drive.  The advantages of this approach include...

+ students keep everything post course,
+ no IT support needed,
+ github transactions are between student and github can be via Github Desktop App

The disadvantages are ...

+ the mayhem of establishing that everyone has RStudio and R up-to-date,
+ the mayhem of student-github credentials (that would be true with or without server),
+ the mayhem of package installs and dependencies (which shouldn't be too bad)

Everything is a tradeoff.  So what do you think?

**Comment by SeascapeScience** [comment]
Hi Ben,

I can’t access github from the airport here, so I’m replying by email…

If you can make a Gulf of Maine crop with a handful of relevant data layers that isn’t too big, then yes, I’m fine letting them work on their own computers. We’ll just have to budget time for getting everyone set up.

Cheers,
Nick

**Comment by btupper** [comment]
I think the only wrinkle is if someone shows up with an ancient computer, but I suspect that is unlikely.

**Comment by btupper** [comment]
@SeascapeScience are you able to download and unpack this zipped directory from Google Drive?  

https://drive.google.com/file/d/1dZEFNVlJRa3WGj4qhDcF3JUCb-6wHCTb/view?usp=share_link

**Comment by SeascapeScience** [comment]
Yep!

**Comment by btupper** [comment]
Oooooh, I got a message last night that IT spun up Rstudio Server (rstudio.bigelow.org) for us.  It can wait until we talk, but, rats!, now we really have to choose!

**Comment by btupper** [comment]
We'll stick with the current model where students set up their own platforms.
